### ISSUE TITLE
Article: Why we use system fonts and don't add external fonts

### ISSUE THREAD

**Issue by alex-page** [govau/design-system-site#321]
Discuss the idea of writing up some "Terms of use" - E.g If a user wants to customise the font family to use custom typefaces, we should say that we don't condone this? You know, don't use the DS just for the sake of it and then customise things that ruin accessibility / performance

**Comment by alex-page** [comment]
This issue needs to be split up into multiple tasks
- Why we use system fonts and don't add external fonts
- How to customise without breaking accessibility or performance

**Comment by adamzerella** [comment]
This has been resolved in the `core` rationale:

![image](https://user-images.githubusercontent.com/1501560/57120106-3d34fd80-6db2-11e9-8c6f-ff9b799ec698.png)
