### ISSUE TITLE
How to customise the components without breaking accessibility or performance

### ISSUE THREAD

**Issue by alex-page** [govau/design-system-site#331]
# Feature request

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/designsystem/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/designsystem/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

This is documentation explaining how to get the most out of the components without breaking key functionality.

**Comment by adamzerella** [comment]
I'm going to close this as we haven't yet seen really horrible usage scenarios of the components. The documentation provide the reference on how the component should be used and `core` documents what SASS functionality can be customised.
If we see some bad usage examples in the wild we can reopen this issue later on.
