### ISSUE TITLE
Version number component overlaps search bar in mobile view 

### ISSUE THREAD

**Issue by haydos404** [govau/design-system-site#387]
# Bug report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-site/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-site/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When in mobile view the version number overlaps with the search bar. Seems like the class `componentheader__version` is positioned absolutely and moved up by -1.75rem which doesn't change when flowing into mobile view.

See attachments for image.

## What I expected to happen

Version number either under or above the title correctly.

## Reproducing

- Website URL: https://designsystem.gov.au/components/core/
- Browser: IOS Safari and Firefox on Linux
- Operating system: IOS and Linux

Steps to reproduce:

If on a workstation: 

1. Navigate to provided url
2. Shrink browser window to under 1000px width
3. Observe overlap

If on IOS safari:

1. Navigate to provided url
2. Observe overlap

## Attachments

![overlap](https://user-images.githubusercontent.com/8341602/51100971-56766600-1824-11e9-8e8f-6e77610f38f2.png)

**Comment by alex-page** [comment]
@haydos404 This isssue has been resolved. Feel free to re open the issue if you notice anything odd!
