### ISSUE TITLE
Add a documentation and an example for a main nav with header 

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/design-system-site#397]
# Feature Request
- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-site/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-site/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.
- [x] I've searched the [community forums](https://community.digital.gov.au/c/designsystem) to check for related issues or feature requests

## What feature would you like to request?

An example like below would be greaat

<img src="https://user-images.githubusercontent.com/20184809/51357605-d7c74480-1b13-11e9-9638-f397b69e2ff2.png" alt="A main nav with header" />

**Comment by alex-page** [comment]
Lets close this as the templates should document this.
