### ISSUE TITLE
Developer environment documentation is missing browserlist for autoprefixer

### ISSUE THREAD

**Issue by alex-page** [govau/design-system-site#407]
# Bug report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-site/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-site/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When following the documentation you may experience some odd issues with css rendering related to autoprefixer not being ran on certain browsers. This is because we are missing our `browserlist`:

https://github.com/govau/design-system-site/blob/738e4c3b4a08dd1e7e82bc6fca809799e553a2a7/package.json#L149-L154

## What I expected to happen

Documentation should include `browserlist`

## Reproducing

- Website URL: https://designsystem.gov.au/get-started/development-environment/

**Comment by sukhrajghuman** [comment]
closed by #420
