### ISSUE TITLE
DTA main site mobile / small screen menu issues

### ISSUE THREAD

**Issue by Decrepidos** [govau/design-system-site#460]
DTA main site mobile / small screen menu
Page tested: Simple, clear and fast public services
https://www.dta.gov.au/our-projects/digital-service-platforms-strategy

**Issues and recommendations**

Firstly I strongly advise against using ARIA menus for website navigation. These should only be used for Windows desktop type applications.

**Issues:** 
Role menu is missing child attribute role=menuitem.
Incorrect keyboard mapping. 

- Expected keyboard mapping for an ARIA menu
- Right Arrow: Moves focus to the next item in the menubar. If focus is on the last item, moves focus to the first item.
- Left Arrow: Moves focus to the previous item in the menubar.
- If focus is on the first item, moves focus to the last item.
- Down Arrow: Opens submenu and moves focus to first item in the submenu.
- Up Arrow: Opens submenu and moves focus to last item in the submenu.
- Home: Moves focus to first item in the menubar.
- End: Moves focus to last item in the menubar.
- Esc must close the expanded menu from anywhere on the page.

**Solution 1**: (recommended) Remove all existing ARIA menu attributes and roles: role=menu, aria-haspopup
Implement aria-expanded and aria-controls on the menu button. Aria controls to point to the sub menu container.

**Solution** 2:
Include role=menuitem on the focusable element in the expanded menu. <a href ...
Fix keyboard mapping.

Lastly the method used to label the navigation is not the best approach.

< nav role="navigation" aria-labelledby="main-navigation-label" >
  < h2 class="visually-hidden" id="main-navigation-label">Main navigation</h2 >

This is clumsy and unnecessary. It is also repetitive. 
Screen readers will announce '_Main navigation navigation region' 'Heading level 2 Main navigation'._ Wow! can that get irritating fast.

**Solution**: Remove aria-labelledby and the visually-hidden H2. Implement a simple aria-label="Main" on <nav role="navigation"
And you don't need role=navigation on the < nav >

 Cheers 
Laurence 

-------

# Bug report

- [Yes ] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-site/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [Yes ] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-site/blob/master/CODE_OF_CONDUCT.md).
- [ Yes] I’ve searched for any related issues and avoided creating a duplicate issue.\

**Comment by sukhrajghuman** [comment]
hey @Decrepidos thanks for bringing this up! This GitHub repository is actually for the [Design System website](https://designsystem.gov.au/). 

You will want to post this ticket in the [DTA website repo](https://github.com/govau/dta-website-rebuild) , and somebody from that team will take care of it :)
