### ISSUE TITLE
Make `placehold.it` images hosted locally

### ISSUE THREAD

**Issue by adamzerella** [govau/design-system-site#483]
Bit of security posture improvement, we currently reference our `placehold.it` images from the external site. If placehold.it ever got compromised we could have some pretty interesting images pop up on our government website.

e.g ![image](https://user-images.githubusercontent.com/1501560/54794583-4fdcf280-4c9c-11e9-96c9-339390252642.png) on https://designsystem.gov.au/components/footer/

This would also fix #480

**Comment by sukhrajghuman** [comment]
closed by #497
