### ISSUE TITLE
Reference external libraries from trusted, local sources like our domain

### ISSUE THREAD

**Issue by adamzerella** [govau/design-system-site#484]
As seen on: https://designsystem.gov.au/get-started/download-page/ we reference libraries from unverified repos on GitHub, if these repos got compromised, we would then reference compromised javascript. 

e.g so:     `<script src="https://raw.githubusercontent.com/scottjehl/Respond/master/dest/respond.min.js">`

should become: `<script src="https://designsystem.gov.au/assets/js/respond.min.js">`

make sure to leave a link / credit to the original author in the file.

**Comment by sukhrajghuman** [comment]
closed by #495
