### ISSUE TITLE
Incorrect react export description for `AUheaderBrand`

### ISSUE THREAD

**Issue by adamzerella** [govau/design-system-site#507]
Incorrect export description on `header` component code page:

link: http://localhost:8080/components/header/code/

![image](https://user-images.githubusercontent.com/1501560/55453089-320d7700-5626-11e9-809c-6450d1ff2f8c.png)

`AUheaderBrand` should have a more meaningful description like:

![image](https://user-images.githubusercontent.com/1501560/55453118-510c0900-5626-11e9-9602-8b9f2b9adcbb.png)

**Comment by sukhrajghuman** [comment]
closed by #513
