### ISSUE TITLE
Bad spacing for `Copy` button on React code exports

### ISSUE THREAD

**Issue by adamzerella** [govau/design-system-site#508]
When the React code exports are too long for a particular component, the `Copy` button sits on top of the text.

Preview: https://designsystem.gov.au/components/form/

Or if `form` preview isn't working by now, just fill up the text box with text

### Desktop:
![image](https://user-images.githubusercontent.com/1501560/55453740-d42e5e80-5628-11e9-97da-65c1df96a3fe.png)

### Mobile:
![image](https://user-images.githubusercontent.com/1501560/55453770-f2945a00-5628-11e9-86f8-95ec00b6aab2.png)

**Comment by sukhrajghuman** [comment]
closed by #513
