### ISSUE TITLE
Add design principles to website

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/design-system-site#532]
It should probably go on about page, or possibly a link in the footer

**Comment by adamzerella** [comment]
Main-nav preview:

![image](https://user-images.githubusercontent.com/1501560/57005183-1099ae00-6c19-11e9-9f87-122ce8a74721.png)

@sukhrajghuman From a little bit of testing I don't think it should be shoved into the `About` page, it's already quite long. I'm starting to lean towards making a dedicated `Principles` page like our `Roadmap` page.

Dedicated page? Link it in multiple places?

**Comment by sukhrajghuman** [comment]
closed by #542
