### ISSUE TITLE
Australian spelling of `colour` for site titles

### ISSUE THREAD

**Issue by adamzerella** [govau/design-system-site#535]
The spelling in 'Customise the <strong>color</strong> scheme' should use the AU spelling:

## e.g

![image](https://user-images.githubusercontent.com/1501560/57004634-d4178380-6c13-11e9-97e0-9d9c1ba1216e.png)

![image](https://user-images.githubusercontent.com/1501560/57004604-99ade680-6c13-11e9-87fe-62898cc95620.png)

We also might have some other references lying around the doc lands

Reference: #538

**Comment by sukhrajghuman** [comment]
closed by #540
