### ISSUE TITLE
Broken image on /components/responsive-media

### ISSUE THREAD

**Issue by gordongrace** [govau/design-system-site#544]
# Bug report

- [X] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-site/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [X] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-site/blob/master/CODE_OF_CONDUCT.md).
- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
https://designsystem.gov.au/components/responsive-media/ has a request for img to https://designsystem.gov.au/assets/img/placeholder/800x800.png (currently 404ing).

## What I expected to happen
Image exists.

## Reproducing

- Website URL: https://designsystem.gov.au/assets/img/placeholder/800x800.png
- Browser: All
- Operating system: All

**Comment by sukhrajghuman** [comment]
nice pick up @gordongrace 
It should be  https://designsystem.gov.au/assets/img/placeholder/800X800.png

**Comment by sukhrajghuman** [comment]
fixed by #524
