### ISSUE TITLE
Add ACT Government logo to "Who's using it" section

### ISSUE THREAD

**Issue by gordongrace** [govau/design-system-site#663]
Approval sought and received from relevant ACT Government contact.

Brand guidance available via:
https://www.act.gov.au/__data/assets/pdf_file/0010/1106110/ACTGov-WHOG-Brand-Guidelines.pdf

Logos available via:
https://www.act.gov.au/branding/logos

Stacked variant recommended.

Logo to link to https://www.act.gov.au

**Comment by sukhrajghuman** [comment]
closed by #664
