### ISSUE TITLE
cardTitle in React code snippet example not closed properly

### ISSUE THREAD

**Issue by KiriHoy** [govau/design-system-site#673]
in the react example code snippet for card, where `<AUcardTitle>` is used, it has been closed with a `</h3>` instead of  `</AUcardTitle>`

![Screenshot_2019-09-10 Card overview - Australian Government Design System](https://user-images.githubusercontent.com/34221033/64569238-2c1f7d00-d3a0-11e9-9347-25475b27c6d6.png)

**Comment by EduardoCanale** [comment]
I will correct it
